language: R
sudo: required
cache: packages
dist: trusty
warnings_are_errors: false
before_install:
- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
script:
- R -f tests/render_rmd.R
env:
  matrix:
  - secure: BDC8bnvTmEsQ+h37PM1px5Gz3cqtVZGyzeTmITHtXh1tWc8/Ub8QjYL/yO7QkIEzBb7Y7yJzsm3mL0c8jmGtsf1OwKpAJhMAU/lnYWEabWo1CVaFeWQAycrIcRCcThcAztu3bohhf9UwN3t9iasxHOOgL95pRYBnTY9/9+GLxT7Ko2DLUV2lyJq55AQZbkukoBX7jLyF5Ovlqjd10m4eKJToaBHSxey69lFEXVDQgJZbqWYiFC5onn56Do7cHKomuFxf5I70wRL3ZzHtIrDym60oErhIJ0UqyFkpobYUM1e8YO+cc97892a67QeU1TOF/fqZEidKr6d0aLKr4wQPm4lvwLmYQfW9QCmZwCC+0VA0Uq9yxEw/qy6b8PmiQ7BFR+7UE1uNpEGoc2K7cX/uYoelogaJUUcAif4hDAjN4MboP6iNx0jhK5LXSQwCgdj40BIBXbpB/6duMhYmhLImw6A1QFdjBZRR1yxC1ErSZdT+sfFxrCjD11pBocOnr/Wjzr+hjY8tJwmwcDerULk4wzpkMO6Wixfv3B/SKlruchMIeYxVEbnA+qeDfeklbywImBnveQl/6Mkfs21lvLR2n8+jUWEQYYnHyqjCMFreCe3DHqzQmloepAkdBct7kteRtaHoobNqthc5F4/DrwYqnvMwV9n/v7bIecVJw18y0Hs=
