---
title: "processing-taobao-villages"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(httr)
library(ggmap)
```


## Geocoding taobao villages

There are 1312 taobao villages as of 2017. This is under the google geocoding api limit, yay.

Testing out the geocoding response, put the province and village together
(省 column + 村 column, separate by comma )


```{r}
taobao_villages_2016 <- read_csv('data/taobao-village-list/taobao_village_list_2016.csv',
                            col_names = c(
                              'sheng',
                              'shi',
                              'xian',
                              'xiangzhen',
                              'cun'
                            ),
                            skip=1)
taobao_villages_2016 <- taobao_villages_2016 %>% mutate(., geocodeAdd = paste0(sheng,cun))
taobao_villages_2016 %>% count(xiangzhen)


taobao_villages_subset_2016 <- subset(taobao_villages_2016, xiangzhen == '三合镇' )
#Go through this list and geocode them all !

taobao_villages_subset_2016

# geocode_the_place <- function(geocodeAdd,...) {
#     
#     a <- geocode(geocodeAdd, output='all', messaging=TRUE, override_limit=TRUE)
#       if (status_code(json) == 200) {
#         response <- fromJSON(content(json, as='text'))
#     } else {
#     NULL
#   }
# }
# 
# 
# taobao_geocoded <- taobao_villages_subset_2016 %>%
#   pmap_df(geocode_the_place, geocodeAdd)


```


```{r}
taobao_villages_2016
```

## What are the differences across the years?
```{r}
taobao_villages_2015 <- readxl::read_excel('data/taobao-village-list/taobao-village-list-2015.xlsx',
                            col_names = c(
                              'sheng',
                              'shi',
                              'xian',
                              'xiangzhen',
                              'cun'
                            ),
                            skip=1)




taobao_villages_2015 <- taobao_villages_2015 %>% 
  mutate(., geocodeAdd = paste0(sheng,cun))

taobao_villages_2014 <- readxl::read_excel('data/taobao-village-list/taobao-village-list-2014.xlsx',
                            col_names = c(
                              'sheng',
                              'shi',
                              'xian',
                              'xiangzhen',
                              'cun',
                              'goods_made'
                            ),
                            skip=1)




taobao_villages_2014 <- taobao_villages_2014 %>% 
  mutate(., geocodeAdd = paste0(sheng,cun)) %>%
  dplyr::select(-goods_made)


taobao_villages_2015 %>% count(xian)
taobao_villages_2014 %>% count(xian)

taobao_villages_2014 <- taobao_villages_2014 %>%
                        arrange(sheng)
taobao_villages_2015 <- taobao_villages_2015 %>%
                        arrange(sheng)
taobao_villages_2016 <- taobao_villages_2016 %>%
                        arrange(sheng)

newones <- setdiff(taobao_villages_2016$geocodeAdd, taobao_villages_2015$geocodeAdd)

newone_table_2015_2016 <- setdiff(taobao_villages_2016, taobao_villages_2015)
newone_table_2014_2015 <- setdiff(taobao_villages_2015, taobao_villages_2014)
newone_table_2014_2016 <- setdiff(taobao_villages_2016, taobao_villages_2014)
diffdiff <- setdiff(newone_table_2015_2016, newone_table_2014_2015)

taobao_villages_2015
taobao_villages_2016

```


```{r}
newone_table_2015_2016
newone_table_2014_2015
diffdiff
```

## Did any taobao villages dissapear?
```{r}
intersect(taobao_villages_2014, taobao_villages_2016)
nrow(taobao_villages_2014)
nrow(intersect(taobao_villages_2014, taobao_villages_2016))

```